name: CI

env:
  PROTOC_VERSION: 3.x
  DEFAULT_NODE_VERSION: 15.x  # If changing this, also change jobs.tests.strategy.matrix.node-version
                              # and jobs.post_install_test.strategy.matrix.node-version

on:
  push:
    branches: [master]
    tags: ['**']
  pull_request:

jobs:
  static_analysis:
    name: Static analysis
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ env.DEFAULT_NODE_VERSION }}
        check-latest: true
    - uses: arduino/setup-protoc@v1
      with:
        version: ${{ env.PROTOC_VERSION }}
        repo-token: "${{ github.token }}"
    - uses: dart-lang/setup-dart@v1
      with: {sdk: stable}
    - run: npm install
    - run: npm run build
    - run: npm run check

  tests:
    name: "Tests | Node ${{ matrix.node-version }} | ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        node-version: [15.x, 14.x, 12.x]  # If changing this, also change env.DEFAULT_NODE_VERSION
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true
    - uses: arduino/setup-protoc@v1
      with:
        version: ${{ env.PROTOC_VERSION }}
        repo-token: "${{ github.token }}"
    - uses: dart-lang/setup-dart@v1
      with: {sdk: stable}
    - run: dart --version
    - run: npm install
    - run: npm run build
    - run: npm run test

  post_install_test:
    name: "Test npm postinstall | Node ${{ matrix.node-version }} | ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        node-version: [15.x, 14.x, 12.x]  # If changing this, also change env.DEFAULT_NODE_VERSION
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
      - uses: arduino/setup-protoc@v1
        with:
          version: ${{ env.PROTOC_VERSION }}
          repo-token: "${{ github.token }}"
      - uses: dart-lang/setup-dart@v1
        with: {sdk: stable}
      - run: dart --version
      - run: npm install
      - run: rm ./.dev
      - run: ./node_modules/.bin/ts-node ./tool/prepare-release.ts
      - run: npm run postinstall

  deploy_npm:
    name: Deploy npm
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/') && github.repository == 'sass/embedded-host-node'"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.DEFAULT_NODE_VERSION }}
          check-latest: true
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: "${{ secrets.NPM_TOKEN }}"
